### ISSUE TITLE
Error in 'partially_connected_hexagonal_mesh'

### ISSUE THREAD

**Issue by Mekholika** [EdgeSimPy/edgesimpy-tutorials#1]
Hello All,

I cannot solve this below error, no mater what I try.
Please help me.
![image](https://github.com/EdgeSimPy/edgesimpy-tutorials/assets/133748684/fe3b0b47-5561-43df-93e9-04b92138b148)

**Comment by paulosevero** [comment]
Hi @Mekholika! Sorry for the delayed response! I'm thrilled you're considering EdgeSimPy for your research endeavors.

It seems you're attempting to create an EdgeSimPy dataset, as the function `partially_connected_hexagonal_mesh` has built-in logic for generating a network topology for datasets.

The way `partially_connected_hexagonal_mesh` is currently implemented, it takes the number of network nodes and automatically determines the number of links needed to connect these nodes. The thing is, the function also expects you to provide delay and bandwidth specifications for all these links.

While you've correctly set up a dictionary with `delay` and `bandwidth` specs for the links, the `number_of_objects` attribute is incorrect, given the size of your network topology. In fact, this is what EdgeSimPy's error message is trying to inform: "You should change the `number_of_objects` value from 16 to 58".

You just have to change the `number_of_objects` to 58, and this should work correctly.

> But, at this point, you might be wondering: How could I know beforehand that the topology would generate exactly 58 links based on the number of network nodes I specified? Well, in fact, that's a current implementation limitation. You must run the algorithm once, and it will return an error telling you the expected number of link specifications. After that, you can adjust accordingly, and the algorithm's workflow will proceed smoothly.

Feel free to reach out if you have any more questions.
