### ISSUE TITLE
working with users and services to make requests

### ISSUE THREAD

**Issue by nazaninSgh** [EdgeSimPy/edgesimpy-tutorials#2]
Hello,
I've been working with edgesimpy to simulate a network where users are associated with applications that consist of stateless services. I have defined user, service and app parameters but I can't figure out why I'm getting a keyerror on line 108 of user.py. It's related to access patterns. 
`access_history[str(app.id)] = self.access_patterns[str(app.id)].history`
Can you provide any guidance, resources or examples on how to use these classes together? More specifically how to associate users to applications and make requests.
I have attached the notebook I've been working on.
[mysim.zip](https://github.com/EdgeSimPy/edgesimpy-tutorials/files/13932726/mysim.zip)

Thank you in advance for your assistance

**Comment by paulosevero** [comment]
Hi @nazaninSgh,

I already have addressed your question via email, but I will also write it here to assist others who may encounter the same issue.

The error in your source code indicates that EdgeSimPy is complaining that a given user does not have a defined access pattern. In general, access patterns are necessary attributes for users as they define when they will access their applications. Access patterns in EdgeSimPy allow us to model various simulation scenarios with varying workloads (e.g., scenarios where users display intermittent access to applications). A general explanation of how access patterns work in EdgeSimPy can be found in section 4.2.4 of EdgeSimPy's paper (attached to the email).

To fix the source-code issue, I modified the eighth cell of the Jupyter notebook, adding the following code chunk inside the for loop:

```python
CircularDurationAndIntervalAccessPattern(
    user=user,
    app=app,
    start=1,
    duration_values=[float("inf")],
    interval_values=[0],
)
```

The above code chunk creates a `CircularDurationAndIntervalAccessPattern` entity attached to the current user being iterated in the for loop. The created access pattern entity essentially defines that the related user will start accessing the application from step 1 and will not stop until the end of the simulation (i.e., based on the values of the `duration_values` and `interval_values` parameters).

After this modification, the eighth cell of the Jupyter Notebook looks like this:

```python
# Create users with pathway mobility model
for i in range(2):
    user = User()
    user.mobility_model = pathway
    user._set_initial_position(coordinates=random.choice(map_coordinates))
    user._connect_to_application(app,2.0)

    # Defining the user's access pattern
    CircularDurationAndIntervalAccessPattern(
        user=user,
        app=app,
        start=1,
        duration_values=[float("inf")],
        interval_values=[0],
    )
```

Simply adding this small code chunk, the Jupyter Notebook works as expected.

I recommend referring to the following repository that contain research artifacts with the current version of EdgeSimPy (v.1.1.0):
- **Thea:** This paper primarily focuses on the placement of composite applications at the edge, considering application QoS requirements (Latency and Privacy) and the infrastructure's power consumption. Thea's manuscript is available at [IEEE Xplore](https://doi.org/10.1109/PDP59025.2023.00028). You can check out the source code ([link here](https://github.com/paulosevero/thea)) to see how we made the whole simulation process, from creating the dataset to designing the placement strategies and automating the experiments.

I hope these instructions allow you to progress in your research using EdgeSimPy. Please reach out if you have any further questions.

Best Regards,
Paulo.
